name: Push Docker image
on:
  push:
    tags:
      - "v*"

env: 
  IMAGE_NAME: mikes-recipes
  DOCKERFILE_PATH: "Presentation/MikesRecipes.WebApi/Dockerfile"

jobs:
  push_docker_image:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout.
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx.
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub.
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Get image version.
        run: |
          Write-Host "Github ref: $Env:GITHUB_REF"
          $version = ./GetVersion.ps1 -RowContainingVersion $Env:GITHUB_REF
            
          if ($version -eq $null) {
            Write-Error "Image version not found."
             exit 1
          }
            
          if ($Env:GITHUB_REF -notlike "*$version") {
            Write-Error "Invalid tag format."
             exit 1
           }
          
          Write-Host "Extracted version: $version"
          echo "IMAGE_VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
        shell: pwsh
          
      - name: Build and push image.
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: | 
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest 
          file: ${{ env.DOCKERFILE_PATH }}
